### ISSUE TITLE
Error pulling GOES/XRS data on Windows?

### ISSUE THREAD

**Issue by jwreep** [sunpy/sunpy#5300]
### Description

I get an error (TypeError: cannot unpack non-iterable NotImplementedType object) pulling GOES/XRS data from SunPy on Windows using the code below.  This works with no issues on MacOS.  

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-400b67f69c2d> in <module>
      6 files = Fido.fetch(result)
      7 
----> 8 goes = timeseries.TimeSeries(files, concatenate=True, )
      9 goes = goes.truncate('2013-11-05 22:00','2013-11-05 23:00')

C:\ProgramData\Anaconda3\lib\site-packages\sunpy\timeseries\timeseries_factory.py in __call__(self, silence_errors, *args, **kwargs)
    404         for filepath in filepaths:
    405             try:
--> 406                 new_ts = self._check_registered_widgets(filepath=filepath, **kwargs)
    407                 new_timeseries.append(new_ts)
    408             except (NoMatchError, MultipleMatchError, ValidationFunctionError):

C:\ProgramData\Anaconda3\lib\site-packages\sunpy\timeseries\timeseries_factory.py in _check_registered_widgets(self, **kwargs)
    527         units = kwargs.pop('units', None)
    528         if filepath:
--> 529             data, meta, units = WidgetType._parse_file(filepath)
    530 
    531         # Now return a TimeSeries from the given file.

TypeError: cannot unpack non-iterable NotImplementedType object
```

### Expected vs Actual behavior

The files download on MacOS and can be analyzed without issue.

### Steps to Reproduce

```python
from sunpy.time import parse_time
from sunpy import timeseries
from sunpy.net import Fido, attrs as a

result = Fido.search(
    a.Time('2013/11/04 06:00', '2013/11/06 00:00'),
    a.Instrument.xrs,
) 
files = Fido.fetch(result)

goes = timeseries.TimeSeries(files, concatenate=True, ) 
goes = goes.truncate('2013-11-05 22:00','2013-11-05 23:00')
```

### System Details

==============================
SunPy Installation Information
==============================

#######
General
#######
Time : Monday, 03. May 2021 09:03PM UT
System : Windows
Processor : AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
Arch : 64bit
SunPy : 2.1.4
OS: Windows 10 10.0.19041 (AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD)

##################
Required Libraries
##################
Python: 3.8.3
NumPy: 1.20.1
SciPy: 1.6.2
matplotlib: 3.3.4
Astropy: 4.2.1
Pandas: 1.2.4
parfive: 1.3.0

#####################
Recommended Libraries
#####################
beautifulsoup: 4.9.3
PyQt4: NOT INSTALLED
PyQt5: 5.9.2
Zeep: 4.0.0
Sqlalchemy: 1.4.7
drms: 0.6.1

**Comment by nabobalis** [comment]
Thanks for the report @jwreep. I will have to test this on a windows system. 

I do have a question tho, did the files download ok on windows and are openable directly? 

Normally that error occurs when the file download has failed in some manner and the files are corrupt or blank.

**Comment by jwreep** [comment]
Looks like it to me.  I can load it with netcdf4, at least:

```
import netCDF4 as nc
fn = 'C:\\Users\\jeffr\\sunpy\\data\\sci_gxrs-l2-irrad_g15_d20131106_v0-0-0.nc'
ds = nc.Dataset(fn)
print(ds)
```

```
<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    Conventions: ACDD-1.3, Spase v2.2.6
    title: GOES 1-15 L2 XRS high-resolution Irradiances
    id:  
    summary: The X-ray flux product consists of reprocessed science-quality high-resolution X-ray solar measurements. The GOES X-Ray Sensor (XRS) measures in a short wavelength channel (XRS-A) with a nominal bandpass of 0.05 to 0.4 nm and in a longer wavelength channel (XRS-B) with a bandpass of 0.1 to 0.8 nm. 

For the given bandpass, the XRS response is based on a flat spectrum beginning with GOES-3. A true solar spectrum is assumed for GOES 1-2.

GOES 13-15 measurements are at 2-s cadence. 
GOES 1-12 measured at a 3-s cadence. 

For GOES 3-12, the XRS-A response was originally determined assuming a bandpass of 0.05 to 0.3 nm.
    keywords: NumericalData.MeasurementType.Irradiance
    keywords_vocabulary: SPASE: Space Physics Archive Search and Extract Data Model version 2.2.6, GCMD: NASA Global Change Master Directory (GCMD) Earth Science Keywords version 8.5
    naming_authority: gov.nesdis.noaa
    history: See algorithm information.
    source: GOES XRS counts
    processing_level: Level 2
    processing_level_description: Derived products
    license: These data may be redistributed and used without restriction. 
    acknowledgment: TBD
    metadata_link: 
    date_created:  
    creator_name: Erika Zetterlund, Janet Machol
    creator_type: person
    creator_institution: DOC/NOAA/NCEI/CCOG/STP
    creator_email: goesr.exis@noaa.gov
    creator_url: https://www.ncei.noaa.gov/
    institution: DOC/NOAA/NESDIS> U.S. Department of Commerce, National Oceanic and Atmospheric Administration, National Environmental Satellite, Data, and Information Services
    publisher_name: National Centers for Environmental Information
    publisher_type: institution
    publisher_institution: DOC/NOAA/NESDIS/NCEI
    publisher_email: goesr.exis@noaa.gov
    publisher_url: https://www.ncei.noaa.gov/
    references: README FOR SCIENCE QUALITY GOES 13-15 XRS DATA
    instrument: GOES 1-15 X-ray Irradiance Sensor (XRS)
    instrument_id:  
    orbital_slot:  
    program: Geostationary Operational Environmental Satellite (GOES)
    project: Geostationary Operational Environmental Satellite (GOES) Solar Terrestrial Physics at NCEI
    platform:  
    L1b_system_environment:  
    L1b_production_site:  
    time_coverage_start:  
    time_coverage_end:  
    time_coverage_resolution: PT2S
    processing_parameters_file:  
    algorithm: 
    algorithm_version:  
    algorithm_date:  
    algorithm_parameters: None
    input_system_environments:  
    input_files_first:  
    input_files_last:  
    input_files_total:  
    dimensions(sizes): time(42151)
    variables(dimensions): int32 a_counts(time), int32 b_counts(time), float32 a_flux(time), float32 b_flux(time), uint16 a_flags(time), uint16 b_flags(time), uint32 a_swpc_flags(time), uint32 b_swpc_flags(time), float64 time(time)
    groups: 
```
